# Core Blockchain Configuration
blockchain:
  # Network configuration
  network: "testnet"  # testnet, mainnet
  
  # Core blockchain RPC URLs
  testnet_url: "https://rpc.test.btcs.network"
  mainnet_url: "https://rpc.coredao.org"
  
  # Chain IDs
  testnet_chain_id: 1115
  mainnet_chain_id: 1116
  
  # Contract addresses
  contract_address: "0x594fc12B3e3AB824537b947765dd9409DAAAa143"  # ModernTensorAI_Optimized - DEPLOYED
  core_token_address: "0x7B74e4868c8C500D6143CEa53a5d2F94e94c7637"  # Mock CORE token (ultra-low testnet)
  btc_token_address: "0x44Ed1441D79FfCb76b7D6644dBa930309E0E6F31"   # Mock BTC token (ultra-low testnet)
  
  # Gas configuration
  gas_price: 20000000000  # 20 gwei
  gas_limit: 6000000
  
  # Transaction timeouts
  transaction_timeout: 120  # seconds
  
  # Required confirmations for finality
  required_confirmations: 12

# Mining and Validation Parameters
mining:
  # Minimum stake requirements
  min_miner_stake: "0.05"      # 0.05 CORE (ultra-low for faucet limitations)
  min_validator_stake: "0.08"  # 0.08 CORE (ultra-low for faucet limitations)
  
  # Consensus parameters
  consensus_window: 300        # 5 minutes consensus rounds
  min_consensus_validators: 2  # Reduced from 3 for testnet
  consensus_threshold: 5000    # 50% threshold (reduced from 66.67%)
  
  # Incentive parameters  
  incentive_decay: 9800        # 98% decay rate per epoch
  btc_boost_multiplier: 12000  # 120% boost for Bitcoin staking (reduced from 150%)

# AI Model Parameters
ai:
  max_model_size: 104857600    # 100MB max model size
  task_timeout: 3600          # 1 hour task timeout
  min_task_reward: 100000000000000000   # 0.1 CORE minimum
  max_task_reward: 1000000000000000000  # 1 CORE maximum

# Bitcoin Integration
bitcoin:
  # Bitcoin RPC configuration
  rpc_url: "https://bitcoin-rpc.com"
  
  # Staking configuration
  staking_enabled: true
  min_lock_time: 86400  # 24 hours in seconds
  
  # Verification settings
  verification_enabled: true
  min_confirmations: 6

# HTTP Client Settings  
http:
  timeout: 30
  max_connections: 100
  retry_attempts: 3
  retry_delay: 1.0 