# ModernTensor Core - Production Configuration
# Updated with correct deployed contract addresses

production:
  # Core Blockchain Configuration
  network:
    name: "Core Testnet"
    chain_id: 1115
    rpc_url: "https://rpc.test.btcs.network"
    explorer_url: "https://scan.test.btcs.network"
    
  # Production Smart Contract Addresses (CORRECT DEPLOYED ADDRESSES)
  contracts:
    # Main ModernTensor contract - DEPLOYED & VERIFIED
    moderntensor_main: "0x594fc12B3e3AB824537b947765dd9409DAAAa143"
    
    # Token contracts for testing (ultra-low stakes)
    core_token: "0x7B74e4868c8C500D6143CEa53a5d2F94e94c7637"    # Mock CORE token
    btc_token: "0x44Ed1441D79FfCb76b7D6644dBa930309E0E6F31"     # Mock BTC token
    
    # Future mainnet addresses (TBD)
    mainnet:
      moderntensor_main: "TBD"
      core_token: "TBD" 
      btc_token: "TBD"

  # Staking Configuration
  staking:
    # Minimum stake amounts (in wei for CORE tokens)
    minimums:
      miner_stake: 100000000000000000000      # 100 CORE tokens (ultra-low for testing)
      validator_stake: 1000000000000000000000  # 1000 CORE tokens (ultra-low for testing)
      
    # Production minimums (for mainnet)
    production_minimums:
      miner_stake: 10000000000000000000000     # 10,000 CORE tokens
      validator_stake: 100000000000000000000000 # 100,000 CORE tokens
      
    # Bitcoin staking tiers
    bitcoin_tiers:
      base:
        multiplier: 1.0
        min_btc: 0
        
      boost:
        multiplier: 1.25
        min_btc: 1000000  # 0.01 BTC in satoshis
        
      super:
        multiplier: 1.5
        min_btc: 10000000  # 0.1 BTC in satoshis
        
      satoshi:
        multiplier: 2.0
        min_btc: 100000000  # 1.0 BTC in satoshis

  # Gas Configuration
  gas:
    price: 20000000000  # 20 gwei
    limit: 300000       # Standard gas limit
    priority_fee: 2000000000  # 2 gwei priority fee

  # Security Settings
  security:
    max_retry_attempts: 3
    timeout_seconds: 30
    enable_signature_verification: true
    
  # Performance Settings  
  performance:
    batch_size: 50
    concurrent_requests: 10
    cache_ttl: 300  # 5 minutes

# Environment-specific overrides
environments:
  development:
    contracts:
      moderntensor_main: "0x594fc12B3e3AB824537b947765dd9409DAAAa143"
    staking:
      minimums:
        miner_stake: 50000000000000000000     # 50 CORE (dev testing)
        validator_stake: 80000000000000000000  # 80 CORE (dev testing)
        
  staging:
    contracts:
      moderntensor_main: "0x594fc12B3e3AB824537b947765dd9409DAAAa143"
    staking:
      minimums:
        miner_stake: 100000000000000000000     # 100 CORE  
        validator_stake: 1000000000000000000000 # 1000 CORE
        
  production:
    # Use production minimums
    network:
      chain_id: 1116  # Core mainnet
      rpc_url: "https://rpc.coredao.org"
      explorer_url: "https://scan.coredao.org"